version: '3'
services:
  frontend:
    build: frontend
    image: zoltannz/kafka-spark-project-frontend:latest
    ports:
      - "80:80"
  backend:
    build: backend
    image: zoltannz/kafka-spark-project-backend:latest
    environment:
      KAFKA_CONNECT: kafka:9092
      ZOOKEEPER_CONNECT: zookeeper:2181
    ports:
      - "3000:3000"
  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka:latest
    environment:
#      KAFKA_ADVERTISED_HOST_NAME: 192.168.1.2
      HOSTNAME_COMMAND: "route -n | awk '/UG[ \t]/{print $$2}'"
      KAFKA_CREATE_TOPICS: "boerse.dev:1:1"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_ZOOKEEPER_CONNECTION_TIMEOUT_MS: "60000"
      KAFKA_ZOOKEEPER_SESSION_TIMEOUT_MS: "60000"
      KAFKA_ZOOKEEPER_SYNC_TIME_MS: "60000"
    ports:
      - "9092:9092"
    volumes:
      - ./kafka/volumes/docker.sock:/var/run/docker.sock
      - ./kafka/volumes/kafka:/kafka
