version: '3'
services:
  frontend:
    build: frontend
    image: zoltannz/kafka-spark-project-frontend:latest
    ports:
      - "80:80"
  backend:
    build: backend
    image: zoltannz/kafka-spark-project-backend:latest
    ports:
      - "3000:3000"
  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka:latest
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    ports:
      - "9092"
